apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-app
  template:
    metadata:
      labels:
        app: session-app
    spec:
      containers:
      - name: session-container
        image: yourdockerhub/session-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: session-secrets
              key: redis_url
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: session-secrets
              key: db_url