apiVersion: apps/v1
kind: Deployment
metadata:
  name: session-app
  labels:
    app: session-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: session-app
  template:
    metadata:
      labels:
        app: session-app
    spec:
      containers:
      - name: session-container
        image: ${DOCKER_USERNAME}/session-app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"
        env:
        - name: PORT
          value: "8080"
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: session-secrets
              key: redis_url
        - name: DB_URL
          valueFrom:
            secretKeyRef:
              name: session-secrets
              key: db_url
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: session-secrets
              key: jwt_secret
        - name: TOKEN_EXPIRATION
          value: "24"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5