apiVersion: v1
kind: Service
metadata:
  name: session-service
spec:
  selector:
    app: session-app
  ports:
  - port: 80
    targetPort: 8080
  type: LoadBalancer

# k8s/secrets.yaml
apiVersion: v1
kind: Secret
metadata:
  name: session-secrets
type: Opaque
data:
  redis_url: cmVkaXM6Ly9yZWRpcy1zZXJ2aWNlOjYzNzkvMA== # redis://redis-service:6379/0
  db_url: cG9zdGdyZXM6Ly9wb3N0Z3Jlcy1zZXJ2aWNlOjU0MzIvc2Vzc2lvbl9kYj9zc2xtb2RlPWRpc2FibGU= # postgres://postgres-service:5432/session_db?sslmode=disable
  jwt_secret: Y2hhbmdlLXRoaXMtdG8tYS1zdHJvbmctc2VjcmV0LWluLXByb2R1Y3Rpb24= # change-this-to-a-strong-secret-in-production

# k8s/redis-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: redis:7
        ports:
        - containerPort: 6379
        resources:
          limits:
            cpu: "300m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "128Mi"